id: P71C5F4CB
initial_creation_type: input
source_metadata:
  title: Tsok Series
  language: en
  description: 'Lotsawa House presents the following texts related to the practice
    of tsok (tshogs) or feast-gathering (Skt. gaṇacakra):'
  volume:
    01f5d902b1144b5693867aa970f10ad0:
      title: Introduction to Gaṇacakra (Tsok)
      parent: Introduction
    13f5cb237f4f42909d88d88ef28c7505:
      title: A Concise Explanation of Gaṇacakra
      parent: Explanation
    2ef77ea7b55a4f65ac6e7a751d897540:
      title: 'A Bouquet of Uḍumbara Flowers: An Explanation of the Tenth Day'
      parent: Explanation
    0ca47875a4d242d0ad82a15299840e97:
      title: 'Music to Adorn the Illusory Display: A Concise Explanation of the Nature
        of the Feast Offering'
      parent: Explanation
    4e3dfdced26148858ac1f02674492209:
      title: The Gaṇacakra Ritual
      parent: Explanation
    87a79b603d0546be998238343266a0e1:
      title: 'Sweet Droplets of the Honey of Accomplishment: A Concise Explanation
        of the Indispensable Points of the Feast-Gathering'
      parent: Explanation
    97cb6211878f45c78fb89fb6b0ab41ae:
      title: 'Bestowing the Glory of Wisdom: A Gaṇacakra Feast for Nyingtik Saldrön'
      parent: Offering Liturgies
    2f5a0995ed904d1790ab32e1ad6fe809:
      title: 'A Glorious Garland of the Two Accomplishments: An Abridged Feast-Offering
        for the Female Practice of the Ḍākinī'
      parent: Offering Liturgies
    f92e7830aa254b9ebdd8b8d92d2566fa:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Prayers
    f75412eea141481f9e17cd6ce96e10e7:
      title: 'Essence of Accomplishment: A Concise Feast-Offering to Noble Tārā'
      parent: Prayers
    421cd4b485a144e98dd692f86f0d2996:
      title: Short Tsok Offering to the Powerful Lady Kurukullā
      parent: Prayers
    5d85bdf4552e44f99c233dad93dea08c:
      title: Brief Prayer of the Feast Gathering
      parent: Prayers
    f1709f54eb1e4a5a9b7f307c2fd77cc1:
      title: Confession and Fulfilment Insert for Accumulating the Practice of Turning
        Back the Summons of the Ḍākinīs
      parent: Prayers
    72885bf9bd1144baba29cb58e0e5057b:
      title: Food Offering Prayer
      parent: Prayers
    2f212ca72dfe46c9ad1223694d226d2f:
      title: Concise Tsok Feast
      parent: Prayers
    1567ba3e67654d33819597b9019967fc:
      title: 'Excellent Vase of Splendour: The Tsok Feast Offering to Accompany the
        Vajra Seven-Line Prayer'
      parent: Prayers
    b356e29561f9405f84de6b9ca8b83b74:
      title: A Concise Feast Prayer
      parent: Prayers
    7bdc874f6be94f56a796021f520786a3:
      title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
      parent: Remainder Offering
    db569f749de641b9bafb417ee28450ab:
      title: The Song of the Vajra
      parent: Songs
    86cfd4b0bba84271afb5e1420e2c74c6:
      title: 'Ḍākinī’s Delight: A Song of the Feast'
      parent: Songs
    d13f33c0667d430c997f72885d9e7e94:
      title: 'Harmonious Clouds of Sublime and Lasting Bliss: A Vajra Song for the
        Tsok Feast Offering to Venerable and Exalted Vajrayoginī'
      parent: Songs
    a55a300dda114e6590ce938d597c0a4a:
      title: 'Song and Dance to Delight the Ḍākas and Ḍākinīs: An Aspiration for the
        Sixfold Satisfaction of the Maṇḍala of the Feast-Gathering'
      parent: Songs
    e41a29487d0446c5aa13421cb487dfcf:
      title: Song of the Feast (Tsok Lu)
      parent: Songs
created_at: '2022-03-01T06:26:39.641575'
last_modified_at: '2022-03-01T06:26:39.641583'
